# Copyright (c) 2026-present Akshit Garg <git+openmvs-metal@akshit.network>
# Codex sign-off: OpenAI Codex assisted with this file.

if(NOT DEFINED TEST_SOURCE_DIR)
	message(FATAL_ERROR "TEST_SOURCE_DIR is required")
endif()

get_filename_component(TEST_SOURCE_DIR "${TEST_SOURCE_DIR}" ABSOLUTE)

function(read_required path out_var)
	if(NOT EXISTS "${path}")
		message(FATAL_ERROR "required source file not found: ${path}")
	endif()
	file(READ "${path}" content)
	set(${out_var} "${content}" PARENT_SCOPE)
endfunction()

function(require_contains label haystack needle)
	string(FIND "${haystack}" "${needle}" found)
	if(found EQUAL -1)
		message(FATAL_ERROR "${label}: missing '${needle}'")
	endif()
endfunction()

function(require_absent label haystack needle)
	string(FIND "${haystack}" "${needle}" found)
	if(NOT found EQUAL -1)
		message(FATAL_ERROR "${label}: unexpected '${needle}'")
	endif()
endfunction()

function(require_list_contains label items expected)
	list(FIND items "${expected}" found)
	if(found EQUAL -1)
		message(FATAL_ERROR "${label}: missing '${expected}'")
	endif()
endfunction()

function(require_order label haystack first second)
	string(FIND "${haystack}" "${first}" first_pos)
	string(FIND "${haystack}" "${second}" second_pos)
	if(first_pos EQUAL -1)
		message(FATAL_ERROR "${label}: missing first marker '${first}'")
	endif()
	if(second_pos EQUAL -1)
		message(FATAL_ERROR "${label}: missing second marker '${second}'")
	endif()
	if(NOT first_pos LESS second_pos)
		message(FATAL_ERROR "${label}: '${first}' must appear before '${second}'")
	endif()
endfunction()

function(require_regex label haystack pattern)
	string(REGEX MATCH "${pattern}" match "${haystack}")
	if(match STREQUAL "")
		message(FATAL_ERROR "${label}: missing pattern '${pattern}'")
	endif()
endfunction()

read_required("${TEST_SOURCE_DIR}/CMakeLists.txt" root_cmake)
read_required("${TEST_SOURCE_DIR}/.gitignore" gitignore_file)
read_required("${TEST_SOURCE_DIR}/AGENTS.md" root_agents)
read_required("${TEST_SOURCE_DIR}/vcpkg.json" root_manifest)
read_required("${TEST_SOURCE_DIR}/.github/workflows/continuous_integration.yml" ci_workflow)
read_required("${TEST_SOURCE_DIR}/.github/workflows/cuda_verification.yml" cuda_workflow)
read_required("${TEST_SOURCE_DIR}/docker/buildInDocker.sh" docker_build)
read_required("${TEST_SOURCE_DIR}/scripts/verify-cuda.sh" cuda_verify_script)
read_required("${TEST_SOURCE_DIR}/scripts/verify-cuda-docker.sh" cuda_verify_docker_script)
read_required("${TEST_SOURCE_DIR}/apps/Tests/RunCudaVerifierSelfTest.cmake" cuda_verifier_self_test)
read_required("${TEST_SOURCE_DIR}/apps/Tests/RunCudaVerifierEarlyFailureSmoke.cmake" cuda_verifier_smoke)
read_required("${TEST_SOURCE_DIR}/ports/siftgpu/vcpkg.json" siftgpu_manifest)
read_required("${TEST_SOURCE_DIR}/ports/siftgpu/portfile.cmake" siftgpu_portfile)
read_required("${TEST_SOURCE_DIR}/ports/siftgpu/source/CMakeLists.txt" siftgpu_source_cmake)
read_required("${TEST_SOURCE_DIR}/apps/CreateStructure/CreateStructure.cpp" create_structure)
read_required("${TEST_SOURCE_DIR}/apps/DensifyPointCloud/DensifyPointCloud.cpp" densify_app)
read_required("${TEST_SOURCE_DIR}/apps/ExtractKeyframes/ExtractKeyframes.cpp" extract_keyframes)
read_required("${TEST_SOURCE_DIR}/libs/Common/CMakeLists.txt" common_cmake)
read_required("${TEST_SOURCE_DIR}/libs/MVS/CMakeLists.txt" mvs_cmake)
read_required("${TEST_SOURCE_DIR}/libs/Common/UtilCUDA.h" util_cuda_h)
read_required("${TEST_SOURCE_DIR}/libs/Common/UtilCUDA.cpp" util_cuda_cpp)
read_required("${TEST_SOURCE_DIR}/libs/Common/UtilCUDADevice.h" util_cuda_device_h)
read_required("${TEST_SOURCE_DIR}/libs/Common/UtilGPU.h" util_gpu_h)
read_required("${TEST_SOURCE_DIR}/libs/Common/UtilGPU.cpp" util_gpu_cpp)
read_required("${TEST_SOURCE_DIR}/libs/Common/UtilMetal.h" util_metal_h)
read_required("${TEST_SOURCE_DIR}/libs/Common/UtilMetal.mm" util_metal_mm)
read_required("${TEST_SOURCE_DIR}/libs/Common/AGENTS.md" common_agents)
read_required("${TEST_SOURCE_DIR}/libs/Common/README.md" common_readme)
read_required("${TEST_SOURCE_DIR}/libs/SFM/FeaturesExtractor.cpp" features_extractor)
read_required("${TEST_SOURCE_DIR}/libs/SFM/PairsMatcher.cpp" pairs_matcher)
read_required("${TEST_SOURCE_DIR}/libs/SFM/GlobalPositioning.cpp" global_positioning)
read_required("${TEST_SOURCE_DIR}/libs/SFM/GlobalPositioning.h" global_positioning_h)
read_required("${TEST_SOURCE_DIR}/apps/Tests/RunMVSAppBackendParity.cmake" app_backend_parity)
read_required("${TEST_SOURCE_DIR}/apps/Tests/RunMVSInProcessBackendSpeed.cmake" in_process_backend_speed)
read_required("${TEST_SOURCE_DIR}/apps/Tests/RunMetalAppFixture.cmake" metal_app_fixture)
read_required("${TEST_SOURCE_DIR}/apps/Tests/RunInvalidGpuBackend.cmake" invalid_backend_test)
read_required("${TEST_SOURCE_DIR}/apps/Tests/Tests.cpp" tests_main)
read_required("${TEST_SOURCE_DIR}/apps/Tests/TestsMVS.cpp" tests_mvs)
read_required("${TEST_SOURCE_DIR}/libs/MVS/PatchMatchCUDA.cpp" patch_match_cuda_cpp)
read_required("${TEST_SOURCE_DIR}/libs/MVS/SceneRefineCUDA.cpp" scene_refine_cuda_cpp)
read_required("${TEST_SOURCE_DIR}/libs/MVS/SceneRefineMetal.cpp" scene_refine_metal_cpp)
read_required("${TEST_SOURCE_DIR}/libs/MVS/SceneDensify.cpp" scene_densify)
read_required("${TEST_SOURCE_DIR}/libs/MVS/AGENTS.md" mvs_agents)
read_required("${TEST_SOURCE_DIR}/libs/MVS/README.md" mvs_readme)
read_required("${TEST_SOURCE_DIR}/apps/RefineMesh/RefineMesh.cpp" refine_mesh_app)
read_required("${TEST_SOURCE_DIR}/apps/Viewer/Scene.h" viewer_scene_h)
read_required("${TEST_SOURCE_DIR}/apps/Viewer/Scene.cpp" viewer_scene_cpp)
read_required("${TEST_SOURCE_DIR}/apps/Viewer/UI.cpp" viewer_ui)
read_required("${TEST_SOURCE_DIR}/docs/metal-port.md" metal_port_doc)
read_required("${TEST_SOURCE_DIR}/docs/architecture.md" architecture_doc)
read_required("${TEST_SOURCE_DIR}/docs/pipelines.md" pipelines_doc)
read_required("${TEST_SOURCE_DIR}/docs/pipeline-traces.md" pipeline_traces_doc)
read_required("${TEST_SOURCE_DIR}/docs/features_catalog.md" features_catalog_doc)
read_required("${TEST_SOURCE_DIR}/docs/suggestions.md" suggestions_doc)

file(GLOB_RECURSE cuda_runtime_surface_files LIST_DIRECTORIES false RELATIVE "${TEST_SOURCE_DIR}"
	"${TEST_SOURCE_DIR}/libs/*"
	"${TEST_SOURCE_DIR}/ports/siftgpu/source/src/*"
)
list(FILTER cuda_runtime_surface_files INCLUDE REGEX "^(libs/.*/CUDA/|libs/.*(CUDA|Cuda|cuda).*|libs/.*\\.cu$|ports/siftgpu/source/src/.*(CU|Cu|CUDA|Cuda|cuda).*|ports/siftgpu/source/src/.*\\.cu$)")
list(SORT cuda_runtime_surface_files)
set(expected_cuda_runtime_surface_files
	"libs/Common/UtilCUDA.cpp"
	"libs/Common/UtilCUDA.h"
	"libs/Common/UtilCUDADevice.h"
	"libs/MVS/CUDA/Camera.h"
	"libs/MVS/CUDA/Maths.h"
	"libs/MVS/PatchMatchCUDA.cpp"
	"libs/MVS/PatchMatchCUDA.cu"
	"libs/MVS/PatchMatchCUDA.h"
	"libs/MVS/PatchMatchCUDA.inl"
	"libs/MVS/SceneRefineCUDA.cpp"
	"libs/MVS/SceneRefineCUDA.cu"
	"libs/MVS/SceneRefineCUDA.inl"
	"ports/siftgpu/source/src/CuTexImage.cpp"
	"ports/siftgpu/source/src/CuTexImage.h"
	"ports/siftgpu/source/src/ProgramCU.cu"
	"ports/siftgpu/source/src/ProgramCU.h"
	"ports/siftgpu/source/src/PyramidCU.cpp"
	"ports/siftgpu/source/src/PyramidCU.h"
	"ports/siftgpu/source/src/SiftMatchCU.cpp"
	"ports/siftgpu/source/src/SiftMatchCU.h"
)
foreach(cuda_surface_file IN LISTS cuda_runtime_surface_files)
	list(FIND expected_cuda_runtime_surface_files "${cuda_surface_file}" found)
	if(found EQUAL -1)
		message(FATAL_ERROR "unclassified CUDA runtime surface: ${cuda_surface_file}")
	endif()
endforeach()
foreach(cuda_surface_file IN LISTS expected_cuda_runtime_surface_files)
	require_list_contains("CUDA runtime surface inventory" "${cuda_runtime_surface_files}" "${cuda_surface_file}")
endforeach()

require_contains("Apple CUDA cache guard" "${root_cmake}" "SET(OpenMVS_USE_CUDA OFF CACHE BOOL \"Enable CUDA library\" FORCE)")
require_contains("CUDA verification require option" "${root_cmake}" "OPTION(OpenMVS_REQUIRE_CUDA")
require_contains("CUDA verification require guard" "${root_cmake}" "OpenMVS_REQUIRE_CUDA=ON requires OpenMVS_USE_CUDA=ON")
require_contains("CUDA verification compiler guard" "${root_cmake}" "OpenMVS_REQUIRE_CUDA=ON but no CUDA compiler was found")
require_contains("CUDA vcpkg feature selection" "${root_cmake}" "IF(OpenMVS_USE_CUDA)")
require_contains("CUDA vcpkg feature selection" "${root_cmake}" "LIST(APPEND VCPKG_MANIFEST_FEATURES \"cuda\")")
require_order("Apple CUDA guard before vcpkg CUDA feature selection" "${root_cmake}" "SET(OpenMVS_USE_CUDA OFF CACHE BOOL \"Enable CUDA library\" FORCE)" "IF(OpenMVS_USE_CUDA)")
require_contains("Metal non-Apple platform guard" "${root_cmake}" "IF(OpenMVS_USE_METAL AND NOT APPLE)")
require_contains("Metal non-Apple platform guard" "${root_cmake}" "SET(OpenMVS_USE_METAL OFF CACHE BOOL \"Enable Apple Metal library\" FORCE)")
require_contains("Metal Objective-C++ language gate" "${root_cmake}" "if(OpenMVS_USE_METAL)")
require_contains("Metal Objective-C++ language gate" "${root_cmake}" "ENABLE_LANGUAGE(OBJCXX)")
require_contains("Metal framework linkage" "${root_cmake}" "FIND_LIBRARY(FOUNDATION_LIBRARY Foundation REQUIRED)")
require_contains("Metal framework linkage" "${root_cmake}" "FIND_LIBRARY(METAL_LIBRARY Metal REQUIRED)")
require_contains("Metal framework linkage" "${root_cmake}" "LIST(APPEND OpenMVS_EXTRA_LIBS \${FOUNDATION_LIBRARY} \${METAL_LIBRARY})")
require_contains("SiftGPU vcpkg feature selection" "${root_cmake}" "IF(OpenMVS_USE_SIFTGPU)")
require_contains("SiftGPU vcpkg feature selection" "${root_cmake}" "LIST(APPEND VCPKG_MANIFEST_FEATURES \"siftgpu\")")
read_required("${TEST_SOURCE_DIR}/apps/CMakeLists.txt" apps_cmake)
require_contains("Viewer build option gates Viewer app" "${apps_cmake}" "if(OpenMVS_BUILD_VIEWER)")
require_contains("Viewer build option gates Viewer app" "${apps_cmake}" "ADD_SUBDIRECTORY(Viewer)")
require_contains("CUDA MVS pipeline CTest registration" "${root_cmake}" "if(_USE_CUDA)")
require_contains("CUDA MVS pipeline CTest registration" "${root_cmake}" "ADD_TEST(NAME MVSPipelineCudaTest")
require_contains("CPU MVS pipeline strict backend" "${root_cmake}" "ADD_TEST(NAME MVSPipelineTest COMMAND $<TARGET_FILE:Tests> \"2\" \"0\" \"1\" \"cpu\")")
require_contains("Metal MVS pipeline strict backend" "${root_cmake}" "ADD_TEST(NAME MVSPipelineMetalTest COMMAND $<TARGET_FILE:Tests> \"2\" \"0\" \"0\" \"metal\")")
require_contains("CUDA MVS pipeline strict backend" "${root_cmake}" "ADD_TEST(NAME MVSPipelineCudaTest COMMAND $<TARGET_FILE:Tests> \"2\" \"0\" \"0\" \"cuda\")")
require_contains("CUDA in-process speed CTest registration" "${root_cmake}" "ADD_TEST(NAME MVSInProcessCpuCudaSpeedTest")
require_contains("CUDA in-process speed CTest script" "${root_cmake}" "RunMVSInProcessBackendSpeed.cmake")
require_contains("CUDA in-process speed reference backend" "${root_cmake}" "-DTEST_REFERENCE_BACKEND=cpu")
require_contains("CUDA in-process speed candidate backend" "${root_cmake}" "-DTEST_CANDIDATE_BACKEND=cuda")
require_contains("CUDA in-process speed CTest timeout" "${root_cmake}" "SET_TESTS_PROPERTIES(MVSInProcessCpuCudaSpeedTest PROPERTIES TIMEOUT 1200 RESOURCE_LOCK OpenMVSMVSTestData)")
require_contains("Metal in-process speed CTest registration" "${root_cmake}" "ADD_TEST(NAME MVSInProcessCpuMetalSpeedTest")
require_contains("Metal in-process speed CTest script" "${root_cmake}" "RunMVSInProcessBackendSpeed.cmake")
require_contains("Metal in-process speed reference backend" "${root_cmake}" "-DTEST_REFERENCE_BACKEND=cpu")
require_contains("Metal in-process speed candidate backend" "${root_cmake}" "-DTEST_CANDIDATE_BACKEND=metal")
require_contains("Metal in-process speed CTest timeout" "${root_cmake}" "SET_TESTS_PROPERTIES(MVSInProcessCpuMetalSpeedTest PROPERTIES TIMEOUT 1200 RESOURCE_LOCK OpenMVSMVSTestData)")
require_contains("CUDA app parity CTest registration" "${root_cmake}" "ADD_TEST(NAME MVSAppCpuCudaParityTest")
require_regex("CUDA app parity independent registration" "${root_cmake}" "if\\(_USE_CUDA\\)[^\n]*\n[ \t]*ADD_TEST\\(NAME MVSAppCpuCudaParityTest")
require_contains("CUDA app parity backend" "${root_cmake}" "-DTEST_CANDIDATE_BACKEND=cuda")
require_contains("CUDA app parity harness" "${root_cmake}" "RunMVSAppBackendParity.cmake")
require_contains("CUDA verifier self-test registration" "${root_cmake}" "ADD_TEST(NAME CudaVerifierSelfTest")
require_contains("CUDA verifier self-test UNIX gate" "${root_cmake}" "if(UNIX)")
require_contains("CUDA verifier self-test script" "${root_cmake}" "RunCudaVerifierSelfTest.cmake")
require_contains("CUDA verifier early-failure smoke registration" "${root_cmake}" "ADD_TEST(NAME CudaVerifierEarlyFailureSmokeTest")
require_contains("CUDA verifier early-failure smoke UNIX gate" "${root_cmake}" "if(UNIX)")
require_contains("CUDA verifier early-failure smoke script" "${root_cmake}" "RunCudaVerifierEarlyFailureSmoke.cmake")
require_contains("Viewer no-CUDA linkage optional target" "${root_cmake}" "if(TARGET Viewer)")
require_contains("Viewer no-CUDA linkage optional target" "${root_cmake}" "-DTEST_BINARY_18=$<TARGET_FILE:Viewer>")
require_contains("Invalid backend CTest registration" "${root_cmake}" "ADD_TEST(NAME MVSInvalidGpuBackendTest")
require_contains("Invalid backend CTest registration" "${root_cmake}" "RunInvalidGpuBackend.cmake")
require_contains("Invalid backend CTest work dir handoff" "${root_cmake}" "-DTEST_WORK_DIR=\${CMAKE_CURRENT_BINARY_DIR}")
require_contains("Metal scene-file app parity CTest registration" "${root_cmake}" "ADD_TEST(NAME MVSAppCpuMetalSceneFileParityTest")
require_contains("Metal scene-file app parity backend" "${root_cmake}" "-DTEST_CANDIDATE_BACKEND=metal")
require_contains("Metal scene-file app parity harness" "${root_cmake}" "RunMVSAppBackendParity.cmake")
require_contains("Metal scene-file app parity timeout" "${root_cmake}" "SET_TESTS_PROPERTIES(MVSAppCpuMetalSceneFileParityTest PROPERTIES TIMEOUT 900)")
require_absent("Metal app parity duplicate heavy registration" "${root_cmake}" "ADD_TEST(NAME MVSAppCpuMetalParityTest")
require_absent("Metal app parity duplicate heavy timeout" "${root_cmake}" "SET_TESTS_PROPERTIES(MVSAppCpuMetalParityTest")
require_contains("CUDA app parity timeout" "${root_cmake}" "SET_TESTS_PROPERTIES(MVSAppCpuCudaParityTest PROPERTIES TIMEOUT 900)")
require_contains("Metal fixture expected Densify marker" "${root_cmake}" "-DTEST_EXPECTED_DENSIFY_BACKEND=metal")
require_contains("Metal fixture expected Refine marker" "${root_cmake}" "-DTEST_EXPECTED_REFINE_BACKEND=metal")
require_contains("No-Metal fixture expected Densify fallback marker" "${root_cmake}" "-DTEST_EXPECTED_DENSIFY_BACKEND=cpu")
require_contains("No-Metal fixture expected Refine fallback marker" "${root_cmake}" "-DTEST_EXPECTED_REFINE_BACKEND=cpu")
require_contains("Docker CUDA proof guard" "${docker_build}" "-DOpenMVS_USE_CUDA=ON -DOpenMVS_REQUIRE_CUDA=ON")
require_contains("Docker CUDA compiler path" "${docker_build}" "-DCMAKE_CUDA_COMPILER=/usr/local/cuda/bin/nvcc")
require_contains("Docker CUDA toolkit root" "${docker_build}" "-DCUDAToolkit_ROOT=/usr/local/cuda")
require_contains("Docker CUDA architecture scope" "${docker_build}" "-DCMAKE_CUDA_ARCHITECTURES=all-major")
require_absent("Docker CUDA proof should not pass nvcc directory as executable" "${docker_build}" "-DCUDA_NVCC_EXECUTABLE=/usr/local/cuda/bin/")
require_absent("Docker CUDA proof should not pass cudart directory as library" "${docker_build}" "-DCUDA_CUDART_LIBRARY=/usr/local/cuda/lib64")
require_absent("Docker CUDA proof should not use legacy include-dir hint" "${docker_build}" "-DCUDA_INCLUDE_DIRS=/usr/local/cuda/include")
require_contains("Local CUDA verifier requires CUDA" "${cuda_verify_script}" "-DOpenMVS_USE_CUDA=ON")
require_contains("Local CUDA verifier requires CUDA guard" "${cuda_verify_script}" "-DOpenMVS_REQUIRE_CUDA=ON")
require_contains("Local CUDA verifier disables Metal" "${cuda_verify_script}" "-DOpenMVS_USE_METAL=OFF")
require_contains("Local CUDA verifier low-memory build default" "${cuda_verify_script}" "OPENMVS_CUDA_BUILD_JOBS:-2")
require_contains("Local CUDA verifier low-memory vcpkg default" "${cuda_verify_script}" "OPENMVS_CUDA_VCPKG_JOBS:-\${build_jobs}")
require_contains("Local CUDA verifier exports vcpkg concurrency" "${cuda_verify_script}" "export VCPKG_MAX_CONCURRENCY=\"\${effective_vcpkg_max_concurrency}\"")
require_contains("Local CUDA verifier serial CTest default" "${cuda_verify_script}" "OPENMVS_CUDA_CTEST_JOBS:-1")
require_contains("Local CUDA verifier serial CTest execution" "${cuda_verify_script}" "--parallel \"\${ctest_jobs}\"")
require_contains("Local CUDA verifier evidence dir" "${cuda_verify_script}" "OPENMVS_CUDA_EVIDENCE_DIR")
require_contains("Local CUDA verifier evidence manifest" "${cuda_verify_script}" "write_evidence_manifest()")
require_contains("Local CUDA verifier evidence manifest" "${cuda_verify_script}" "evidence-manifest.log")
require_contains("Local CUDA verifier evidence manifest hashes" "${cuda_verify_script}" "sha256sum")
require_contains("Local CUDA verifier evidence manifest columns" "${cuda_verify_script}" "path\\tbytes\\tsha256")
require_contains("Local CUDA verifier finalizer" "${cuda_verify_script}" "finalize_evidence()")
require_contains("Local CUDA verifier result evidence" "${cuda_verify_script}" "verification-result.log")
require_contains("Local CUDA verifier result status" "${cuda_verify_script}" "exit_status=%s")
require_contains("Local CUDA verifier result success marker" "${cuda_verify_script}" "result=success")
require_contains("Local CUDA verifier result failure marker" "${cuda_verify_script}" "result=failure")
require_contains("Local CUDA verifier manifest on early failure" "${cuda_verify_script}" "trap 'finalize_evidence \"$?\"' EXIT")
require_contains("Local CUDA verifier environment evidence" "${cuda_verify_script}" "verification-environment.log")
require_contains("Local CUDA verifier records effective vcpkg concurrency early" "${cuda_verify_script}" "effective_vcpkg_max_concurrency")
require_contains("Local CUDA verifier requires NVIDIA hardware evidence" "${cuda_verify_script}" "command -v nvidia-smi")
require_contains("Local CUDA verifier records NVIDIA hardware evidence" "${cuda_verify_script}" "nvidia-smi.log")
require_contains("Local CUDA verifier records NVIDIA GPU list" "${cuda_verify_script}" "nvidia-smi-gpus.log")
require_contains("Local CUDA verifier requires visible GPU" "${cuda_verify_script}" "grep -Eq '^GPU [0-9]+:'")
require_contains("Local CUDA verifier records tool versions" "${cuda_verify_script}" "tool-versions.log")
require_contains("Local CUDA verifier records nvcc version when available" "${cuda_verify_script}" "nvcc --version")
require_contains("Local CUDA verifier requires git source-state evidence" "${cuda_verify_script}" "git is required for CUDA verification source-state evidence")
require_contains("Local CUDA verifier records source-state evidence" "${cuda_verify_script}" "source-state.log")
require_contains("Local CUDA verifier records git head" "${cuda_verify_script}" "git_head=")
require_contains("Local CUDA verifier records git status" "${cuda_verify_script}" "git status --short")
require_contains("Local CUDA verifier records git diff stat" "${cuda_verify_script}" "git diff --stat")
require_contains("Local CUDA verifier configure evidence" "${cuda_verify_script}" "configure.log")
require_contains("CUDA verifier evidence ignored" "${gitignore_file}" "cuda-verification-evidence/")
require_contains("CUDA verifier default build dir ignored" "${gitignore_file}" "build-*/")
require_contains("Local CUDA verifier cache CUDA assertion" "${cuda_verify_script}" "OpenMVS_USE_CUDA:BOOL=ON")
require_contains("Local CUDA verifier cache required assertion" "${cuda_verify_script}" "OpenMVS_REQUIRE_CUDA:BOOL=ON")
require_contains("Local CUDA verifier cache Metal assertion" "${cuda_verify_script}" "OpenMVS_USE_METAL:BOOL=OFF")
require_contains("Local CUDA verifier generated CUDA assertion" "${cuda_verify_script}" "#define _USE_CUDA")
require_contains("Local CUDA verifier generated Metal assertion" "${cuda_verify_script}" "/* #undef _USE_METAL */")
require_contains("Local CUDA verifier cache evidence copy" "${cuda_verify_script}" "\${evidence_dir}/CMakeCache.txt")
require_contains("Local CUDA verifier config evidence copy" "${cuda_verify_script}" "\${evidence_dir}/ConfigLocal.h")
require_contains("Local CUDA verifier vcpkg status parser" "${cuda_verify_script}" "require_vcpkg_status_feature()")
require_contains("Local CUDA verifier self-test mode" "${cuda_verify_script}" "OPENMVS_CUDA_SELF_TEST")
require_contains("Local CUDA verifier self-test parser success" "${cuda_verify_script}" "require_vcpkg_status_feature \"\${good_status}\" siftgpu cuda")
require_contains("Local CUDA verifier self-test parser failure" "${cuda_verify_script}" "self-test expected missing siftgpu[cuda] to fail")
require_contains("Local CUDA verifier vcpkg CUDA package assertion" "${cuda_verify_script}" "require_vcpkg_status_feature \"\${vcpkg_status}\" cuda core")
require_contains("Local CUDA verifier vcpkg Ceres CUDA feature assertion" "${cuda_verify_script}" "require_vcpkg_status_feature \"\${vcpkg_status}\" ceres cuda")
require_contains("Local CUDA verifier vcpkg SiftGPU CUDA feature assertion" "${cuda_verify_script}" "require_vcpkg_status_feature \"\${vcpkg_status}\" siftgpu cuda")
require_contains("Local CUDA verifier vcpkg status evidence copy" "${cuda_verify_script}" "\${evidence_dir}/vcpkg-status")
require_contains("Local CUDA verifier vcpkg manifest log evidence copy" "${cuda_verify_script}" "\${evidence_dir}/vcpkg-manifest-install.log")
require_contains("Local CUDA verifier targeted build" "${cuda_verify_script}" "--target Tests DensifyPointCloud ReconstructMesh RefineMesh")
require_contains("Local CUDA verifier build evidence" "${cuda_verify_script}" "build.log")
require_contains("Local CUDA verifier registration check" "${cuda_verify_script}" "proof_test_regex=")
require_contains("Local CUDA verifier registration check" "${cuda_verify_script}" "MVSPipelineCudaTest|MVSInProcessCpuCudaSpeedTest|MVSAppCpuCudaParityTest|MVSInvalidGpuBackendTest|MVSMetalCudaSurfaceAuditTest|SecondaryCudaSurfaceAuditTest|CudaVerifierSelfTest|CudaVerifierEarlyFailureSmokeTest")
require_contains("Local CUDA verifier registration evidence" "${cuda_verify_script}" "ctest-registration.log")
require_contains("Local CUDA verifier app parity run" "${cuda_verify_script}" "MVSAppCpuCudaParityTest")
require_contains("Local CUDA verifier pipeline run" "${cuda_verify_script}" "MVSPipelineCudaTest")
require_contains("Local CUDA verifier in-process speed run" "${cuda_verify_script}" "MVSInProcessCpuCudaSpeedTest")
require_contains("Local CUDA verifier in-process speed registration" "${cuda_verify_script}" "grep -q 'MVSInProcessCpuCudaSpeedTest'")
require_contains("Local CUDA verifier invalid backend registration" "${cuda_verify_script}" "grep -q 'MVSInvalidGpuBackendTest'")
require_contains("Local CUDA verifier MVS audit registration" "${cuda_verify_script}" "grep -q 'MVSMetalCudaSurfaceAuditTest'")
require_contains("Local CUDA verifier secondary audit registration" "${cuda_verify_script}" "grep -q 'SecondaryCudaSurfaceAuditTest'")
require_contains("Local CUDA verifier self-test registration" "${cuda_verify_script}" "grep -q 'CudaVerifierSelfTest'")
require_contains("Local CUDA verifier early-failure smoke registration" "${cuda_verify_script}" "grep -q 'CudaVerifierEarlyFailureSmokeTest'")
require_contains("Local CUDA verifier source audits" "${cuda_verify_script}" "MVSMetalCudaSurfaceAuditTest|SecondaryCudaSurfaceAuditTest")
require_contains("Local CUDA verifier test evidence" "${cuda_verify_script}" "ctest.log")
require_contains("Local CUDA verifier Densify CUDA marker evidence" "${cuda_verify_script}" "candidate DensifyPointCloud backend marker: cuda")
require_contains("Local CUDA verifier RefineMesh CUDA marker evidence" "${cuda_verify_script}" "candidate RefineMesh backend marker: cuda")
require_contains("Local CUDA verifier same-mesh CUDA marker evidence" "${cuda_verify_script}" "candidate same-mesh RefineMesh backend marker: cuda")
require_contains("Local CUDA verifier in-process CUDA marker evidence" "${cuda_verify_script}" "candidate MVSPipelineTest backend marker: cuda")
require_contains("Local CUDA verifier Densify speed evidence" "${cuda_verify_script}" "DensifyPointCloud elapsed: reference=")
require_contains("Local CUDA verifier RefineMesh speed evidence" "${cuda_verify_script}" "RefineMesh elapsed: reference=")
require_contains("Local CUDA verifier same-mesh speed evidence" "${cuda_verify_script}" "same-mesh RefineMesh elapsed: reference=")
require_contains("Local CUDA verifier in-process speed evidence" "${cuda_verify_script}" "MVSPipelineTest elapsed: reference=")
require_contains("Local CUDA verifier parity evidence summary" "${cuda_verify_script}" "backend-parity-summary.log")
require_contains("Local CUDA verifier summary evidence" "${cuda_verify_script}" "CUDA verification succeeded")
require_contains("Local CUDA verifier records vcpkg jobs" "${cuda_verify_script}" "vcpkg_jobs=%s")
require_contains("Local CUDA verifier records CTest jobs" "${cuda_verify_script}" "ctest_jobs=%s")
require_contains("Local CUDA verifier records vcpkg concurrency" "${cuda_verify_script}" "VCPKG_MAX_CONCURRENCY=%s")
require_contains("CUDA verifier self-test env" "${cuda_verifier_self_test}" "OPENMVS_CUDA_SELF_TEST=1")
require_contains("CUDA verifier self-test success marker" "${cuda_verifier_self_test}" "CUDA verifier self-test passed")
require_contains("CUDA verifier smoke fake nvidia-smi" "${cuda_verifier_smoke}" "set(fake_nvidia_smi")
require_contains("CUDA verifier smoke fake PATH" "${cuda_verifier_smoke}" "\"PATH=\${shim_dir}:\$ENV{PATH}\"")
require_contains("CUDA verifier smoke temp evidence dir" "${cuda_verifier_smoke}" "OPENMVS_CUDA_EVIDENCE_DIR=\${evidence_dir}")
require_contains("CUDA verifier smoke expects failure" "${cuda_verifier_smoke}" "CUDA verifier early-failure smoke unexpectedly succeeded")
require_contains("CUDA verifier smoke expects status 1" "${cuda_verifier_smoke}" "expected 1")
require_contains("CUDA verifier smoke result evidence" "${cuda_verifier_smoke}" "verification-result.log")
require_contains("CUDA verifier smoke failure marker" "${cuda_verifier_smoke}" "result=failure")
require_contains("CUDA verifier smoke manifest evidence" "${cuda_verifier_smoke}" "evidence-manifest.log")
require_contains("CUDA verifier smoke avoids configure" "${cuda_verifier_smoke}" "early-failure smoke should not reach CMake configure")
require_contains("Docker CUDA verifier uses NVIDIA CUDA image" "${cuda_verify_docker_script}" "nvidia/cuda:12.9.1-devel-ubuntu24.04")
require_contains("Docker CUDA verifier requires GPU runtime" "${cuda_verify_docker_script}" "--gpus all")
require_contains("Docker CUDA verifier checks Docker CLI" "${cuda_verify_docker_script}" "require_host_command docker")
require_contains("Docker CUDA verifier checks NVIDIA CLI" "${cuda_verify_docker_script}" "require_host_command nvidia-smi")
require_contains("Docker CUDA verifier persists host probe evidence" "${cuda_verify_docker_script}" "persist_host_probe()")
require_contains("Docker CUDA verifier persists host probe evidence" "${cuda_verify_docker_script}" "trap persist_host_probe EXIT")
require_contains("Docker CUDA verifier evidence manifest" "${cuda_verify_docker_script}" "write_evidence_manifest()")
require_contains("Docker CUDA verifier evidence manifest" "${cuda_verify_docker_script}" "evidence-manifest.log")
require_contains("Docker CUDA verifier manifest includes host probe logs" "${cuda_verify_docker_script}" [=[persist_host_probe() {
	mkdir -p "${evidence_dir}"
	cp -f "${host_probe_dir}"/*.log "${evidence_dir}/" 2>/dev/null || true
	rm -rf "${host_probe_dir}"
	write_evidence_manifest
}]=])
require_contains("Docker CUDA verifier records host NVIDIA runtime" "${cuda_verify_docker_script}" "host-nvidia-smi.log")
require_contains("Docker CUDA verifier records Docker daemon info" "${cuda_verify_docker_script}" "docker-info.log")
require_contains("Docker CUDA verifier records NVIDIA Docker runtime" "${cuda_verify_docker_script}" "docker-nvidia-smi.log")
require_contains("Docker CUDA verifier checks Docker daemon" "${cuda_verify_docker_script}" "docker info > \"\${host_probe_dir}/docker-info.log\"")
require_contains("Docker CUDA verifier checks NVIDIA Docker runtime" "${cuda_verify_docker_script}" "docker run --rm --gpus all \"\${image}\" nvidia-smi > \"\${host_probe_dir}/docker-nvidia-smi.log\"")
require_contains("Docker CUDA verifier mounts current checkout" "${cuda_verify_docker_script}" "-v \"\${source_dir}:/work\"")
require_contains("Docker CUDA verifier uses vcpkg cache" "${cuda_verify_docker_script}" "files,/vcpkg-cache,readwrite")
require_contains("Docker CUDA verifier bootstraps vcpkg" "${cuda_verify_docker_script}" "bootstrap-vcpkg.sh")
require_contains("Docker CUDA verifier uses checked-in proof script" "${cuda_verify_docker_script}" "/work/scripts/verify-cuda.sh")
require_contains("Docker CUDA verifier restores host ownership" "${cuda_verify_docker_script}" "OPENMVS_CUDA_DOCKER_HOST_UID")
require_contains("Docker CUDA verifier restores evidence ownership" "${cuda_verify_docker_script}" "/work/cuda-verification-evidence")
require_contains("Docker CUDA verifier installs compiler toolchain" "${cuda_verify_docker_script}" "build-essential")
require_contains("Docker CUDA verifier installs CMake" "${cuda_verify_docker_script}" "cmake")
require_contains("Docker CUDA verifier installs certificates" "${cuda_verify_docker_script}" "ca-certificates")
require_contains("Docker CUDA verifier installs Python" "${cuda_verify_docker_script}" "python3")
require_contains("Docker CUDA verifier low-memory build default" "${cuda_verify_docker_script}" "OPENMVS_CUDA_BUILD_JOBS:-2")
require_contains("Docker CUDA verifier low-memory vcpkg default" "${cuda_verify_docker_script}" "OPENMVS_CUDA_VCPKG_JOBS:-\${build_jobs}")
require_contains("Docker CUDA verifier serial CTest default" "${cuda_verify_docker_script}" "OPENMVS_CUDA_CTEST_JOBS:-1")
require_contains("Docker CUDA verifier passes vcpkg jobs" "${cuda_verify_docker_script}" "OPENMVS_CUDA_VCPKG_JOBS=\${vcpkg_jobs}")
require_contains("Docker CUDA verifier passes CTest jobs" "${cuda_verify_docker_script}" "OPENMVS_CUDA_CTEST_JOBS=\${ctest_jobs}")
require_contains("Docker CUDA verifier default CMake generator" "${cuda_verify_docker_script}" "OPENMVS_CUDA_GENERATOR:-Ninja")
require_contains("Docker CUDA verifier disables Viewer by default" "${cuda_verify_docker_script}" "-DOpenMVS_BUILD_VIEWER=OFF")
require_contains("Docker CUDA verifier disables Python by default" "${cuda_verify_docker_script}" "-DOpenMVS_USE_PYTHON=OFF")
require_contains("Docker CUDA verifier keeps SiftGPU CUDA surface enabled" "${cuda_verify_docker_script}" "-DOpenMVS_USE_SIFTGPU=ON")
require_contains("Docker CUDA verifier keeps Ceres enabled" "${cuda_verify_docker_script}" "-DOpenMVS_USE_CERES=ON")
require_contains("CUDA workflow manual trigger" "${cuda_workflow}" "workflow_dispatch:")
require_contains("CUDA workflow self-hosted runner" "${cuda_workflow}" "runs-on: [self-hosted, linux, x64, cuda]")
require_absent("CUDA workflow must not preflight before evidence wrapper" "${cuda_workflow}" "Verify host NVIDIA runtime")
require_absent("CUDA workflow must not bypass evidence-preserving wrapper" "${cuda_workflow}" "docker run --rm --gpus all")
require_contains("CUDA workflow uses checked-in Docker verifier" "${cuda_workflow}" "scripts/verify-cuda-docker.sh")
require_contains("CUDA workflow uploads evidence" "${cuda_workflow}" "actions/upload-artifact@v4")
require_contains("CUDA workflow evidence artifact name" "${cuda_workflow}" "cuda-verification-evidence")
require_contains("CUDA workflow uploads evidence on failure" "${cuda_workflow}" "if: always()")
require_contains("CUDA workflow low-memory default" "${cuda_workflow}" "default: \"2\"")
require_contains("CUDA workflow serial CTest default" "${cuda_workflow}" "default: \"1\"")
require_contains("CUDA workflow passes vcpkg jobs" "${cuda_workflow}" "OPENMVS_CUDA_VCPKG_JOBS")
require_contains("CUDA workflow passes CTest jobs" "${cuda_workflow}" "OPENMVS_CUDA_CTEST_JOBS")
require_contains("CUDA workflow timeout default" "${cuda_workflow}" "default: \"1200\"")
require_contains("CUDA workflow CUDA image default" "${cuda_workflow}" "nvidia/cuda:12.9.1-devel-ubuntu24.04")
require_contains("CUDA-off CI Windows matrix" "${ci_workflow}" "os: windows-latest")
require_contains("CUDA-off CI Linux matrix" "${ci_workflow}" "os: ubuntu-latest")
require_contains("CUDA-off CI macOS matrix" "${ci_workflow}" "os: macos-latest")
require_contains("CUDA-off CI Windows triplet" "${ci_workflow}" "triplet: x64-windows-release")
require_contains("CUDA-off CI Linux triplet" "${ci_workflow}" "triplet: x64-linux-release")
require_contains("CUDA-off CI macOS triplet" "${ci_workflow}" "triplet: arm64-osx")
require_contains("CUDA-off CI configure guard" "${ci_workflow}" "-DOpenMVS_USE_CUDA=OFF")
require_contains("CUDA-off CI CTest run" "${ci_workflow}" "ctest --parallel 2 --build-config")

require_contains("MVS test expected backend argument" "${tests_main}" "expectedMVSBackend")
require_contains("MVS test expected backend argument" "${tests_main}" "MVS::PipelineTest(forceCPU, verbose, expectedMVSBackend)")
require_contains("MVS test backend reset" "${tests_mvs}" "SEACAVE::GPU::ResetLastSelectedBackend")
require_contains("MVS test backend strict check" "${tests_mvs}" "SEACAVE::GPU::LastSelectedBackend")
require_contains("MVS test backend strict check" "${tests_mvs}" "MVS pipeline selected backend mismatch")

require_contains("App backend parity marker check" "${app_backend_parity}" "function(require_backend_marker")
require_contains("App backend parity marker check" "${app_backend_parity}" [=[OpenMVS backend selected: ${app} ${backend}]=])
require_contains("App backend parity marker failure" "${app_backend_parity}" "did not report expected backend marker")
require_contains("App backend parity Densify marker" "${app_backend_parity}" "DensifyPointCloud")
require_contains("App backend parity RefineMesh marker" "${app_backend_parity}" "same-mesh RefineMesh")
require_contains("App backend parity stderr capture" "${app_backend_parity}" "ERROR_VARIABLE error")
require_contains("App backend parity speed gate helper" "${app_backend_parity}" "function(require_candidate_faster")
require_contains("App backend parity speed gate failure" "${app_backend_parity}" [=[candidate must be faster than ${TEST_REFERENCE_BACKEND} reference]=])
require_contains("App backend parity Densify speed gate" "${app_backend_parity}" "require_candidate_faster(\"DensifyPointCloud elapsed\"")
require_contains("App backend parity RefineMesh speed gate" "${app_backend_parity}" "require_candidate_faster(\"RefineMesh elapsed\"")
require_contains("App backend parity same-mesh speed gate" "${app_backend_parity}" "require_candidate_faster(\"same-mesh RefineMesh elapsed\"")
require_absent("App backend parity speed gate must not be optional" "${app_backend_parity}" "TEST_REQUIRE_CANDIDATE_FASTER")
require_contains("In-process backend speed marker check" "${in_process_backend_speed}" "function(require_backend_marker")
require_contains("In-process backend speed marker" "${in_process_backend_speed}" "OpenMVS backend selected: DensifyPointCloud")
require_contains("In-process backend speed reference run" "${in_process_backend_speed}" "run_pipeline(\"reference MVSPipelineTest\" 1")
require_contains("In-process backend speed candidate run" "${in_process_backend_speed}" "run_pipeline(\"candidate MVSPipelineTest\" 0")
require_contains("In-process backend speed gate helper" "${in_process_backend_speed}" "function(require_candidate_faster")
require_contains("In-process backend speed gate failure" "${in_process_backend_speed}" [=[candidate must be faster than ${TEST_REFERENCE_BACKEND} reference]=])
require_contains("In-process backend speed gate call" "${in_process_backend_speed}" "require_candidate_faster(\"MVSPipelineTest elapsed\"")
require_contains("App backend parity empty log cleanup" "${app_backend_parity}" "function(remove_empty_app_logs")
require_contains("App backend parity Densify log cleanup" "${app_backend_parity}" "*DensifyPointCloud*.log")
require_contains("App backend parity Reconstruct log cleanup" "${app_backend_parity}" "*ReconstructMesh*.log")
require_contains("App backend parity Refine log cleanup" "${app_backend_parity}" "*RefineMesh*.log")
require_contains("App backend parity empty log cleanup" "${app_backend_parity}" "file(SIZE \"\${app_log}\" app_log_size)")
require_contains("App backend parity empty log cleanup" "${app_backend_parity}" "file(REMOVE \"\${app_log}\")")
require_contains("Metal fixture marker check" "${metal_app_fixture}" "function(require_backend_marker")
require_contains("Metal fixture Densify marker check" "${metal_app_fixture}" "require_backend_marker(DensifyPointCloud")
require_contains("Metal fixture Refine marker check" "${metal_app_fixture}" "require_backend_marker(RefineMesh")
require_contains("Metal fixture expected Densify backend" "${metal_app_fixture}" "TEST_EXPECTED_DENSIFY_BACKEND")
require_contains("Metal fixture expected Refine backend" "${metal_app_fixture}" "TEST_EXPECTED_REFINE_BACKEND")
require_contains("Metal fixture empty log cleanup" "${metal_app_fixture}" "function(remove_empty_app_logs")
require_contains("Metal fixture Densify log cleanup" "${metal_app_fixture}" "*DensifyPointCloud*.log")
require_contains("Metal fixture Reconstruct log cleanup" "${metal_app_fixture}" "*ReconstructMesh*.log")
require_contains("Metal fixture Refine log cleanup" "${metal_app_fixture}" "*RefineMesh*.log")
require_contains("Metal fixture empty log cleanup" "${metal_app_fixture}" "file(REMOVE \"\${app_log}\")")
require_contains("Invalid backend test Densify coverage" "${invalid_backend_test}" "require_invalid_backend_rejected(\"DensifyPointCloud\"")
require_contains("Invalid backend test RefineMesh coverage" "${invalid_backend_test}" "require_invalid_backend_rejected(\"RefineMesh\"")
require_contains("Invalid backend test value" "${invalid_backend_test}" "--gpu-backend vulkan")
require_contains("Invalid backend test marker" "${invalid_backend_test}" "unknown GPU backend 'vulkan'")
require_contains("Invalid backend test empty log cleanup" "${invalid_backend_test}" "file(REMOVE")
require_contains("Invalid backend test preserves existing logs" "${invalid_backend_test}" "list(FIND before_logs")
require_contains("Densify backend marker output" "${scene_densify}" "OpenMVS backend selected: DensifyPointCloud")
require_contains("Densify backend telemetry" "${scene_densify}" "SEACAVE::GPU::SetLastSelectedBackend(selectedDepthBackend)")
require_contains("Densify Metal marker selection" "${scene_densify}" "selectedDepthBackend = SEACAVE::GPU::Backend::METAL")
require_contains("Densify CUDA marker selection" "${scene_densify}" "selectedDepthBackend = SEACAVE::GPU::Backend::CUDA")
require_contains("Densify selected Metal allocation failure blocks CPU fallback" "${scene_densify}" [=[failed to allocate Metal PatchMatch pool; refusing CPU fallback for a requested Metal depth-map backend");
			return false;]=])
require_contains("Densify selected Metal failure blocks CPU fallback" "${scene_densify}" [=[refusing CPU fallback for a selected Metal depth-map backend",
			arrDepthData[idxImage].GetView().GetID());
		return false;]=])
require_contains("Densify depth-map failure is fatal" "${scene_densify}" "bool depthMapEstimated = true")
require_contains("Densify depth-map failure is fatal" "${scene_densify}" "if (!depthMapEstimated)")
require_contains("Densify depth-map failure is fatal" "${scene_densify}" "error: failed to estimate depth-map")
require_contains("Densify invalid backend rejection" "${densify_app}" "ParseBackend(SEACAVE::GPU::desiredBackend) == SEACAVE::GPU::Backend::UNKNOWN")
require_contains("Densify invalid backend rejection" "${densify_app}" "unknown GPU backend")
require_contains("Densify invalid backend stderr" "${densify_app}" "std::fprintf(stderr, \"error: unknown GPU backend")
require_order("Densify invalid backend rejected before MVS init" "${densify_app}" "unknown GPU backend" "MVS::Initialize(APPNAME")
require_contains("RefineMesh backend marker output" "${refine_mesh_app}" "OpenMVS backend selected: RefineMesh")
require_contains("RefineMesh backend telemetry" "${refine_mesh_app}" "SEACAVE::GPU::SetLastSelectedBackend(selectedRefineBackend)")
require_contains("RefineMesh Metal marker selection" "${refine_mesh_app}" "selectedRefineBackend = SEACAVE::GPU::Backend::METAL")
require_contains("RefineMesh CUDA marker selection" "${refine_mesh_app}" "selectedRefineBackend = SEACAVE::GPU::Backend::CUDA")
require_contains("RefineMesh selected Metal failure blocks CPU fallback" "${refine_mesh_app}" "const bool wantsMetalRefine")
require_contains("RefineMesh selected Metal failure blocks CPU fallback" "${refine_mesh_app}" [=[error: Metal mesh refinement failed; refusing CPU fallback for a selected Metal backend");
			return EXIT_FAILURE;]=])
require_order("RefineMesh selected Metal failure returns before CPU fallback" "${refine_mesh_app}" "refusing CPU fallback for a selected Metal backend" "scene.RefineMesh(OPT::nResolutionLevel")
require_contains("RefineMesh invalid backend rejection" "${refine_mesh_app}" "ParseBackend(SEACAVE::GPU::desiredBackend) == SEACAVE::GPU::Backend::UNKNOWN")
require_contains("RefineMesh invalid backend rejection" "${refine_mesh_app}" "unknown GPU backend")
require_contains("RefineMesh invalid backend stderr" "${refine_mesh_app}" "std::fprintf(stderr, \"error: unknown GPU backend")
require_order("RefineMesh invalid backend rejected before MVS init" "${refine_mesh_app}" "unknown GPU backend" "MVS::Initialize(APPNAME")
require_contains("Viewer GPU Densify defaults include Metal" "${viewer_scene_h}" "#if defined(_USE_CUDA) || defined(_USE_METAL)")
require_contains("Viewer Densify backend option" "${viewer_scene_h}" "String gpuBackend{\"auto\"}")
require_contains("Viewer Densify backend dispatch" "${viewer_scene_cpp}" "SEACAVE::GPU::desiredBackend = options.gpuBackend")
require_contains("Viewer Densify backend UI" "${viewer_ui}" "GPU Backend")
require_contains("Viewer Densify backend UI" "${viewer_ui}" "opts.gpuBackend = backendValues[backendIndex]")

require_contains("root manifest CUDA feature" "${root_manifest}" "\"cuda\"")
require_contains("root manifest CUDA feature" "${root_manifest}" "\"features\": [\n            \"cuda\"\n          ]")
require_contains("root manifest SiftGPU feature" "${root_manifest}" "\"siftgpu\"")
require_contains("root manifest SiftGPU non-CUDA dependency" "${root_manifest}" "\"features\": [\n            \"egl\"\n          ]")

require_contains("SiftGPU port CUDA default" "${siftgpu_portfile}" "set(ENABLE_CUDA OFF)")
require_contains("SiftGPU port CUDA feature gate" "${siftgpu_portfile}" "if(\"cuda\" IN_LIST FEATURES)")
require_contains("SiftGPU port CUDA feature gate" "${siftgpu_portfile}" "set(ENABLE_CUDA ON)")
require_contains("SiftGPU manifest CUDA feature" "${siftgpu_manifest}" "\"cuda\"")
require_contains("SiftGPU manifest EGL feature" "${siftgpu_manifest}" "\"egl\"")
require_contains("SiftGPU source CUDA Apple guard" "${siftgpu_source_cmake}" "SET(CUDA_ENABLED OFF)")
require_contains("SiftGPU source CUDA Apple guard" "${siftgpu_source_cmake}" "MESSAGE(STATUS \"Disabling CUDA on MacOS\")")
require_contains("SiftGPU source CUDA manifest gate" "${siftgpu_source_cmake}" "IF(CUDA_ENABLED)")
require_contains("SiftGPU source CUDA manifest gate" "${siftgpu_source_cmake}" "LIST(APPEND VCPKG_MANIFEST_FEATURES \"cuda\")")
require_order("SiftGPU Apple CUDA guard before CUDA language enablement" "${siftgpu_source_cmake}" "SET(CUDA_ENABLED OFF)" "enable_language(CUDA)")
require_contains("SiftGPU source CUDA language gate" "${siftgpu_source_cmake}" "if(CUDA_ENABLED)")
require_contains("SiftGPU source CUDA language gate" "${siftgpu_source_cmake}" "enable_language(CUDA)")
require_contains("SiftGPU source CUDA toolkit gate" "${siftgpu_source_cmake}" "find_package(CUDAToolkit REQUIRED)")
require_contains("SiftGPU source CUDA definitions" "${siftgpu_source_cmake}" "SIFTGPU_CUDA=1 CUDA_SIFTGPU_ENABLED")
require_contains("SiftGPU source CUDA libraries" "${siftgpu_source_cmake}" "CUDA::cudart CUDA::curand")
require_contains("SiftGPU source CUDA optional list" "${siftgpu_source_cmake}" "set(OPTIONAL_CUDA_SRCS)")
require_contains("SiftGPU source CUDA optional list" "${siftgpu_source_cmake}" "src/CuTexImage.h  src/CuTexImage.cpp")
require_contains("SiftGPU source CUDA optional list" "${siftgpu_source_cmake}" "src/ProgramCU.cu  src/ProgramCU.h")
require_contains("SiftGPU source CUDA optional list" "${siftgpu_source_cmake}" "src/PyramidCU.h   src/PyramidCU.cpp")
require_contains("SiftGPU source CUDA optional list" "${siftgpu_source_cmake}" "src/SiftMatchCU.h src/SiftMatchCU.cpp")
require_contains("SiftGPU source CUDA optional target inclusion" "${siftgpu_source_cmake}" "\${OPTIONAL_CUDA_SRCS}")

require_contains("Common Metal Objective-C++ source gate" "${common_cmake}" "if(_USE_METAL)")
require_contains("Common Metal Objective-C++ source" "${common_cmake}" "UtilMetal.mm")
require_contains("Common Metal ARC/module flags" "${common_cmake}" "-fobjc-arc;-fmodules;-fcxx-modules")
require_contains("Common CUDA implementation compile guard" "${util_cuda_h}" "#ifdef _USE_CUDA")
require_contains("Common CUDA implementation compile guard" "${util_cuda_cpp}" "#ifdef _USE_CUDA")
require_order("Common CUDA device helper guarded by UtilCUDA" "${util_cuda_h}" "#ifdef _USE_CUDA" "#include \"UtilCUDADevice.h\"")
require_contains("Common CUDA device selection" "${util_cuda_h}" "GENERAL_API CUresult initDevices")
require_contains("Common CUDA CPU sentinel" "${util_cuda_h}" "GENERAL_API bool isCpuRequested")
require_contains("Common CUDA device memory wrapper" "${util_cuda_h}" "class GENERAL_API MemDevice")
require_contains("Common CUDA array wrapper" "${util_cuda_h}" "class TArrayRT")
require_contains("Common CUDA best device selection" "${util_cuda_cpp}" "_selectBestDevice")
require_contains("Common CUDA CPU sentinel implementation" "${util_cuda_cpp}" "deviceIDs.empty() || deviceIDs == \"-2\"")
require_contains("Common CUDA device helper includes driver API" "${util_cuda_device_h}" "#include <cuda.h>")
require_contains("Common CUDA device helper includes runtime API" "${util_cuda_device_h}" "#include <cuda_runtime.h>")
require_contains("Common CUDA device helper active capability query" "${util_cuda_device_h}" "getActiveDeviceCC")
require_contains("Common CUDA device helper arch mismatch hint" "${util_cuda_device_h}" "CUDA hint: the active device is compute capability")
require_contains("Common CUDA device helper check macro" "${util_cuda_device_h}" "#define CUDA_CHECK(condition)")
require_contains("Common CUDA device helper stream RAII" "${util_cuda_device_h}" "CudaStreamDestructor")
require_contains("Common CUDA device helper shared stream RAII" "${util_cuda_device_h}" "CreateSharedStream")
require_contains("Common GPU backend enum" "${util_gpu_h}" "enum class Backend")
require_contains("Common GPU backend telemetry declaration" "${util_gpu_h}" "GENERAL_API void ResetLastSelectedBackend")
require_contains("Common GPU backend telemetry declaration" "${util_gpu_h}" "GENERAL_API void SetLastSelectedBackend")
require_contains("Common GPU backend telemetry declaration" "${util_gpu_h}" "GENERAL_API Backend LastSelectedBackend")
require_contains("Common GPU backend parse" "${util_gpu_cpp}" "Backend ParseBackend")
require_contains("Common GPU Apple auto policy" "${util_gpu_cpp}" "Backend SelectAutoBackend")
require_contains("Common GPU Apple Metal priority" "${util_gpu_cpp}" "if (applePlatform)")
require_contains("Common GPU backend telemetry implementation" "${util_gpu_cpp}" "static Backend lastSelectedBackend")
require_contains("Common GPU backend telemetry implementation" "${util_gpu_cpp}" "void SetLastSelectedBackend")
require_contains("Common Metal availability" "${util_metal_h}" "GENERAL_API bool isAvailable")
require_contains("Common Metal device info" "${util_metal_h}" "GENERAL_API bool getDefaultDevice")
require_contains("Common Metal shared buffer wrapper" "${util_metal_h}" "class GENERAL_API Buffer")
require_contains("Common Metal texture formats" "${util_metal_h}" "enum class PixelFormat")
require_contains("Common Metal R32 texture format" "${util_metal_h}" "R32Float")
require_contains("Common Metal R16 texture format" "${util_metal_h}" "R16Float")
require_contains("Common Metal texture wrapper" "${util_metal_h}" "class GENERAL_API Texture2D")
require_contains("Common Metal smoke coverage" "${util_metal_h}" "GENERAL_API bool RunSmokeTest")
require_contains("Common Metal default device" "${util_metal_mm}" "MTLCreateSystemDefaultDevice")
require_contains("Common Metal shared buffer allocation" "${util_metal_mm}" "newBufferWithLength:size options:MTLResourceStorageModeShared")
require_contains("Common Metal texture allocation" "${util_metal_mm}" "newTextureWithDescriptor")
require_contains("Common Metal R32 pixel format" "${util_metal_mm}" "MTLPixelFormatR32Float")
require_contains("Common Metal R16 pixel format" "${util_metal_mm}" "MTLPixelFormatR16Float")
require_contains("Common Metal upload helper" "${util_metal_mm}" "bool Buffer::SetData")
require_contains("Common Metal download helper" "${util_metal_mm}" "bool Buffer::GetData")
require_contains("Common Metal fill helper" "${util_metal_mm}" "bool Buffer::Fill")
require_contains("Common Metal texture upload helper" "${util_metal_mm}" "bool Texture2D::SetData")
require_contains("Common Metal texture download helper" "${util_metal_mm}" "bool Texture2D::GetData")
require_contains("Common Metal smoke kernel" "${util_metal_mm}" "kernel void add_one")
require_contains("Common Metal texture smoke kernel" "${util_metal_mm}" "kernel void texture_add")

require_contains("MVS CUDA source gate" "${mvs_cmake}" "if(_USE_CUDA)")
require_contains("MVS CUDA source gate" "${mvs_cmake}" "FILE(GLOB LIBRARY_FILES_CUDA \"*.cu\")")
require_contains("MVS CUDA source gate" "${mvs_cmake}" "LIST(APPEND LIBRARY_FILES_C \${LIBRARY_FILES_CUDA})")
require_contains("MVS Metal source gate" "${mvs_cmake}" "if(_USE_METAL)")
require_contains("MVS Metal source gate" "${mvs_cmake}" "LIST(APPEND LIBRARY_FILES_C \${METAL_LIBRARY_FILES_C})")
require_contains("MVS Metal Objective-C++ flags" "${mvs_cmake}" "-fobjc-arc;-fmodules;-fcxx-modules")
require_contains("MVS Metal generated shader include" "${mvs_cmake}" "PatchMatchMetalShader.inc")
require_contains("MVS Metal generated metallib include" "${mvs_cmake}" "SceneRefineMetalLibrary.inc")
require_contains("PatchMatch CUDA host compile guard" "${patch_match_cuda_cpp}" "#ifdef _USE_CUDA")
require_contains("SceneRefine CUDA host compile guard" "${scene_refine_cuda_cpp}" "#ifdef _USE_CUDA")
require_contains("SceneRefine Metal bridge compile guard" "${scene_refine_metal_cpp}" "#ifdef _USE_METAL")

require_contains("CreateStructure CUDA option guard" "${create_structure}" "#ifdef _USE_CUDA")
require_contains("CreateStructure CUDA option guard" "${create_structure}" "(\"cuda-device\"")
require_contains("CreateStructure CUDA config guard" "${create_structure}" "cfg.matchCfg.useCUDA = cfg.featuresCfg.useCUDA = !SEACAVE::CUDA::isCpuRequested")
require_contains("ExtractKeyframes CUDA option guard" "${extract_keyframes}" "#ifdef _USE_CUDA")
require_contains("ExtractKeyframes CUDA option guard" "${extract_keyframes}" "(\"cuda-device\"")
require_contains("ExtractKeyframes CUDA config guard" "${extract_keyframes}" "config.useCUDA = !SEACAVE::CUDA::isCpuRequested")

require_contains("SiftGPU feature extraction CUDA compile guard" "${features_extractor}" "#ifdef _USE_CUDA")
require_contains("SiftGPU feature extraction CUDA fallback" "${features_extractor}" "constexpr bool useCUDA = false")
require_contains("SiftGPU feature extraction CUDA option gate" "${features_extractor}" "args.push_back(\"-cuda\")")
require_contains("SiftGPU matching CUDA compile guard" "${pairs_matcher}" "#if defined(_USE_SIFTGPU) && defined(_USE_CUDA)")
require_contains("SiftGPU matching CUDA language guard" "${pairs_matcher}" "#ifdef SIFTGPU_CUDA")

require_contains("Ceres CUDA solver guard" "${global_positioning}" "#ifdef _USE_CUDA")
require_contains("Ceres CUDA solver selection" "${global_positioning}" "ceres::CUDA")
require_contains("Ceres Metal fallback" "${global_positioning}" "#elif defined(_USE_METAL)")
require_contains("Ceres Metal fallback" "${global_positioning}" "Ceres has no Metal backend; using CPU solvers instead")
require_contains("Ceres GPU option docs" "${global_positioning_h}" "CUDA is used when compiled, Metal has no Ceres backend")

require_contains("architecture docs mention first-party Metal PatchMatch" "${architecture_doc}" "PatchMatch CUDA/Metal")
require_contains("architecture docs mention first-party Metal refine" "${architecture_doc}" "SceneRefine CUDA/Metal")
require_contains("architecture docs mention Metal backend selector" "${architecture_doc}" "--gpu-backend auto|cpu|cuda|metal")
require_contains("architecture docs mention CUDA best device semantics" "${architecture_doc}" "`-1` selects the best CUDA GPU")
require_contains("architecture docs mention CUDA CPU sentinel semantics" "${architecture_doc}" "`-2`, `cpu`, or an empty value disables CUDA work")
require_contains("Root AGENTS mentions Metal feature flag" "${root_agents}" "OpenMVS_USE_METAL")
require_contains("Root AGENTS mentions CUDA/Metal dependency" "${root_agents}" "**CUDA/Metal**: GPU acceleration")
require_contains("Root AGENTS mentions CUDA/Metal kernels" "${root_agents}" "CUDA/Metal kernels for GPU acceleration")
require_contains("Common AGENTS mentions CUDA/Metal dependency" "${common_agents}" "optional CUDA/Metal")
require_contains("Common README mentions Metal runtime helper" "${common_readme}" "UtilMetal.mm")
require_contains("Common README mentions Metal buffer texture helpers" "${common_readme}" "Apple Metal buffers/textures")
require_contains("Common README mentions shared GPU selector" "${common_readme}" "UtilGPU.cpp")
require_contains("Common README mentions Metal dependency" "${common_readme}" "**Metal** (optional): Apple GPU utilities for first-party MVS paths")
require_contains("MVS AGENTS mentions CUDA/Metal PatchMatch" "${mvs_agents}" "PatchMatchCUDA/PatchMatchMetal")
require_contains("MVS AGENTS mentions Metal refine entry" "${mvs_agents}" "Scene::RefineMeshMetal")
require_contains("MVS AGENTS mentions backend selector" "${mvs_agents}" "--gpu-backend auto|cpu|cuda|metal")
require_contains("MVS AGENTS mentions Metal dependency" "${mvs_agents}" "Apple Metal framework")
require_contains("MVS README mentions CUDA/Metal PatchMatch" "${mvs_readme}" "PatchMatchCUDA` and `PatchMatchMetal`")
require_contains("MVS README has CUDA/Metal GPU section" "${mvs_readme}" "## GPU (CUDA/Metal) Support")
require_contains("MVS README lists Metal PatchMatch files" "${mvs_readme}" "PatchMatchMetal.h/mm/metal")
require_contains("MVS README lists Metal refine files" "${mvs_readme}" "SceneRefineMetal.cpp/mm/metal")
require_contains("MVS README lists Metal camera helpers" "${mvs_readme}" "Metal/Camera.h")
require_contains("MVS README lists Metal math helpers" "${mvs_readme}" "Metal/Maths.h")
require_contains("MVS README mentions Metal dependency" "${mvs_readme}" "**Metal framework** (optional): Apple first-party MVS GPU acceleration")
require_contains("suggestions docs mention CUDA/Metal PatchMatch prior" "${suggestions_doc}" "first-party CUDA/Metal PatchMatch paths")
require_contains("suggestions docs mention CUDA/Metal lowDepths" "${suggestions_doc}" "CUDA/Metal PatchMatch `lowDepths` mechanism")
require_contains("pipeline docs mention first-party Metal PatchMatch" "${pipelines_doc}" "PatchMatchCUDA/PatchMatchMetal")
require_contains("pipeline docs mention CUDA device sentinel semantics" "${pipelines_doc}" "CUDA device not set to `-2`, `cpu`, or empty")
require_contains("pipeline docs mention first-party Metal refine" "${pipelines_doc}" "RefineMeshMetal")
require_contains("pipeline trace docs mention first-party Metal PatchMatch" "${pipeline_traces_doc}" "PatchMatchCUDA/PatchMatchMetal")
require_contains("pipeline trace docs mention CUDA device sentinel semantics" "${pipeline_traces_doc}" "CUDA device not set to `-2`, `cpu`, or empty")
require_contains("pipeline trace docs mention first-party Metal refine" "${pipeline_traces_doc}" "RefineMeshMetal")
require_contains("feature catalog docs mention first-party Metal PatchMatch" "${features_catalog_doc}" "PatchMatchMetal")
require_contains("feature catalog docs mention first-party Metal refine" "${features_catalog_doc}" "SceneRefineMetal")
require_contains("feature catalog docs mention CUDA best device semantics" "${features_catalog_doc}" "`-1` best GPU")
require_contains("feature catalog docs mention CUDA disable sentinel semantics" "${features_catalog_doc}" "`-2`/`cpu`/empty disables CUDA work")
require_contains("Metal status docs validation matrix" "${metal_port_doc}" "## Validation Matrix Status")
require_contains("Metal status docs macOS matrix result" "${metal_port_doc}" "macOS CPU/Metal: complete")
require_contains("Metal status docs CUDA-off matrix result" "${metal_port_doc}" "Windows/Ubuntu/macOS CUDA-off CI: present and source-audited")
require_contains("Metal status docs CUDA-on optional result" "${metal_port_doc}" "Linux/NVIDIA CUDA-on: optional preservation proof")
require_contains("Metal status docs acceptance caveat" "${metal_port_doc}" "completion of this Metal port is judged by Metal-vs-CPU parity and Apple CUDA-free builds")
require_contains("Metal status docs optional CUDA evidence" "${metal_port_doc}" "Optional CUDA evidence:")
require_absent("Root AGENTS should not omit Metal feature flag" "${root_agents}" "OpenMVS_USE_CUDA`, `OpenMVS_USE_CERES")
require_absent("Root AGENTS should not claim CUDA-only dependency" "${root_agents}" "**CUDA**: GPU acceleration")
require_absent("Root AGENTS should not claim CUDA-only kernels" "${root_agents}" "CUDA kernels for GPU acceleration")
require_absent("MVS AGENTS should not claim PatchMatch GPU is CUDA-only" "${mvs_agents}" "**PatchMatchCUDA** (`PatchMatchCUDA.h`): GPU-accelerated depth estimation")
require_absent("MVS AGENTS should not use CUDA-only GPU section" "${mvs_agents}" "## GPU/CUDA Components")
require_absent("MVS AGENTS should not list only CUDA refine path" "${mvs_agents}" "Scene::RefineMeshCUDA(...)                    // GPU")
require_absent("MVS AGENTS should not list only CUDA Toolkit optional dependency" "${mvs_agents}" "Ceres Solver, CUDA Toolkit, Python")
require_absent("architecture docs should not claim MVS GPU is CUDA-only" "${architecture_doc}" "All are disabled by default and require the `_USE_CUDA` build flag")
require_absent("architecture docs should not invert CUDA -1 semantics" "${architecture_doc}" "-1 disables CUDA")
require_absent("MVS README should not claim PatchMatch GPU is CUDA-only" "${mvs_readme}" "PatchMatchCUDA` provides a CUDA implementation for the depth estimation step")
require_absent("MVS README should not use CUDA-only GPU section" "${mvs_readme}" "## GPU (CUDA) Support")
require_absent("MVS README should not claim all GPU fallback is CUDA-only" "${mvs_readme}" "When CUDA is not available, everything falls back to CPU implementations transparently")
require_absent("MVS README should not list only CUDA refine diagram" "${mvs_readme}" "SceneRefineCUDA.cpp (89 KB) - GPU")
require_absent("MVS README should not list CUDA Toolkit as all GPU acceleration" "${mvs_readme}" "**CUDA Toolkit** (optional): GPU acceleration")
require_absent("suggestions docs should not mention only CUDA lowDepths prior" "${suggestions_doc}" "PatchMatchCUDA` already has a `lowDepths` prior mechanism")
require_absent("suggestions docs should not point only to PatchMatchCUDA.inl" "${suggestions_doc}" "lowDepths` in `PatchMatchCUDA.inl")
require_absent("suggestions docs should not point LiDAR only to PatchMatchCUDA" "${suggestions_doc}" "PatchMatchCUDA`'s existing `lowDepths` mechanism")
require_absent("pipeline docs should not use CUDA-only PatchMatch decision" "${pipelines_doc}" "CUDA available?")
require_absent("pipeline docs should not use CUDA-only PatchMatch init" "${pipelines_doc}" "PatchMatchCUDA::Init")
require_absent("pipeline docs should not use stale CUDA device threshold" "${pipelines_doc}" "desiredDeviceID >= 0")
require_absent("pipeline trace docs should not use CUDA-only PatchMatch decision" "${pipeline_traces_doc}" "CUDA available?")
require_absent("pipeline trace docs should not use CUDA-only PatchMatch init" "${pipeline_traces_doc}" "PatchMatchCUDA::Init")
require_absent("pipeline trace docs should not use stale CUDA device threshold" "${pipeline_traces_doc}" "desiredDeviceID >= 0")
require_absent("feature catalog should not label modules as CUDA-only" "${features_catalog_doc}" "CUDA-enabled modules")
require_absent("feature catalog should not claim dense GPU is only PatchMatchCUDA" "${features_catalog_doc}" "GPU Support: Yes (PatchMatchCUDA)")
require_absent("feature catalog should not claim CPU depth only has PatchMatchCUDA GPU variant" "${features_catalog_doc}" "GPU variant is PatchMatchCUDA")

require_absent("Apple CMake should not force SiftGPU CUDA" "${root_cmake}" "SIFTGPU_CUDA")
message(STATUS "Secondary CUDA surface audit passed")
